### ISSUE TITLE
Schedule Andy for Photo Shoot

### ISSUE THREAD

**Issue by sporkius** [NeuronRobotics/DyIO-Kickstarter#1]
Schedule Andy to come do some video and Photos for the Kickstarter.

**Comment by madhephaestus** [comment]
@sporkius can you link here the script?

**Comment by madhephaestus** [comment]
https://docs.google.com/document/d/1TImK6RVIiOUyewB-F9pWQPm6OYGzoOJO5yGSbf1gBxQ/edit
