### ISSUE TITLE
Bluetooth DyIO Software Specs

### ISSUE THREAD

**Issue by sporkius** [NeuronRobotics/DyIO-Kickstarter#12]
Please provide software specs for the bluetooth DyIO. These specs are specifically for the kickstarter page. Please make them clear and concise.

**Comment by madhephaestus** [comment]
This is where i think we flip the narrative from Dyio-centric (Zune model) to Bowler Engine

so the "zune mode" from microsoft was to make a device, and assume everyone knew what to do with it. The "Apple ecosystem" model was a combo of Itunes, podcasts, device syncing, and lastly an ipod itself. This complete solution came in after the zune and crushed it.
to that end
we are not selling "a dyio"
we are selling the: "Bowler Engine"

This is Robotics libraries, Kinematics Libraries, Medical Libraries, Industrial libraries, 3rd party library integration (OpenCV, Google API, JavaFX, Swing, Octave, Joystick libraries) and finally devices (DyIO, Bluetooth DyIO, MRI controller, Industrial controller, Bowler Board). 

We are the ecosystem that arduino could never match, nevermind beat. We are the powerful engine, ease of use and cross platform that ROS could never be. We are the type of system BigDog runs, but open source and as east to learn as an introduction to programming class
then later we can talk details of the DyIO

**Comment by madhephaestus** [comment]
so the story starts with wanting to build robots or robotic systems
but thats hard
normally i would need to be a grad student (ROS) to make something interesting
or simply couldnt do anything that complicated (arduino)
introducing: the Bowler Engine
(this is just me rough-drafting the video script from this perspective)
With the bowler Engine you can use our peowerful robotics control libraries including Kinematics Engine, Mobile Robotics Engine, Networked Modular Robitics engine among may other services and modules.
These are pure java and amaintained by Neuron Robotics Cooperative
In addition to these are integrations with even more powerful 3rd party libraries
Opencv provides access to image processing and object recognition. Tis lets you us any webcam or CHDK camera to add vision to your robot
the Google API provides access to google docs, chat and Hangout calls. Your robot can je just as social as you!
With the Android libbraries you gain access to cellular data, GPS and inertial sensors. Fully mobile robots with fast access to built in sensors.
To provide access to standard sensors and actuators, we are releasing the DyIO and Bluetooth DyIO.
<in sert dyio features and specs>
The Bowler system has been used everywhere from surgical robotics devices to introduction to programming classes for Jr High students.

**Comment by madhephaestus** [comment]
# Bowler Engine Specifications:

## Operating System Support

Windows 
Mac OSX
Linux
Android (3.1 and up with USB host)

##Integrated Development Environments
Eclipse (fully supported with tutorials)
Processing (natively supported by processing for easy transition from Arduino)
Counterclockwise (Clojure native IDE, also available as an eclipse plugin)
Matlab (through external library support)
Gradle and Ant (command line builds)
Intellij, DrJava, and NetBeans are compatible

##Langauges
Java (High speed compiled OO)
Clojure (Functional Programming)
Scala (Functional/OO)
Matlab (Numeric language)
Python (Provided by Jython runtime)
Ruby (Provided by JRuby runtime)
C (native implementation for microcontrollers/PC)
Node.js (experimental clean reimplementation of core in JavaScript)
Any JVM langauge http://en.wikipedia.org/wiki/List_of_JVM_languages

## Speed

 3ms round trip from Java to DyIO over USB (http://neuronrobotics.github.io/Java-Code-Library/Connection-Dialog-Example/)
 .5ms round trip from Java to Java over UDP/TCP (http://neuronrobotics.github.io/Java-Code-Library/UDP-Client-Example/)
 Real-time Java compatible with JamaicaVM (https://www.aicas.com/cms/en/JamaicaVM)

## Robotics Libraries

 Input and output (http://neuronrobotics.github.io/Java-Code-Library/Digital-Input-Example-Simple/)
Real-TIme control loops using PID (http://neuronrobotics.github.io/Java-Code-Library/DyIO-PID-Setup-Example/)
Kinematics Engine (http://neuronrobotics.github.io/Java-Code-Library/Simple-D-H-Parameters-Engine-Example/)

## Additional Libraries

 Image processing and Face Tracking with OpenCV 
 Social networking and collaboration with the Google API
 User Interfaces and multimedia with JavaFX and Swing

**Comment by sporkius** [comment]
I know you have done so much with bowler studio and the software. Is this information still accurate? Is there anything else you need to add.
