### ISSUE TITLE
Review Kickstarter page. 

### ISSUE THREAD

**Issue by sporkius** [NeuronRobotics/DyIO-Kickstarter#8]
Review the kickstarter page and modify as needed. Link is https://www.kickstarter.com/projects/722129475/574507851?token=202a889f

**Comment by madhephaestus** [comment]
The high-value rewards should refer to plated DyIO cases

**Comment by madhephaestus** [comment]
The rewards for the sensor packs and servo packs are missing

**Comment by madhephaestus** [comment]
Rewards for Arm and DyIO and Webcam and DyIO kits missing.

**Comment by madhephaestus** [comment]
"..With an intuitive software package.." should mention NR-Console by name in first paragraph

**Comment by madhephaestus** [comment]
Be careful about all sentences being third person plural referring to "makers", or "builders". Its repetitive, sure, but this is propaganda after all...

**Comment by madhephaestus** [comment]
heh, it should actually say something about google apps...

**Comment by madhephaestus** [comment]
THe three surgeries are not brain surgery, but the prostate brachytherapy

**Comment by madhephaestus** [comment]
Specs and about us are unfinished

**Comment by JohnFiegel** [comment]
we need to review this its shared on Google docs
